# Generated by Django 5.2.12 on 2026-04-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='video_link',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
    ]
