# Generated by Django 5.2.12 on 2026-03-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Адміністратор'), ('organizer', 'Організатор'), ('jury', 'Журі'), ('captain', 'Капітан'), ('player', 'Учасник')], default='player', max_length=20),
        ),
    ]
