# Generated by Django 5.2.12 on 2026-03-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_user_role'),
        ('tournaments', '0002_user_is_verified'),
    ]

    operations = [
    ]
