# Generated by Django 5.2.12 on 2026-03-22 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_merge_0002_alter_user_role_0002_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='status',
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_teams',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reg_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reg_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
