# Generated by Django 5.2.12 on 2026-04-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_evaluation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jury_tournaments',
            field=models.ManyToManyField(blank=True, related_name='jury_members', to='tournaments.tournament'),
        ),
    ]
