# Generated by Django 5.2.12 on 2026-03-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_team_members',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_team_members',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('tournament', 'name')},
        ),
    ]
