# Generated by Django 5.2.12 on 2026-03-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournament_max_team_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='team',
            name='captain_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
