# Generated by Django 5.2.12 on 2026-03-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_team_captain_email_team_captain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Discord тег'),
        ),
    ]
