# Generated by Django 5.2.12 on 2026-03-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_user_discord_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='min_team_members',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
