# Generated by Django 5.2.12 on 2026-03-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_alter_tournament_min_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто / школа / організація'),
        ),
    ]
