from django.urls import path

from . import views

urlpatterns = [
    path('auth/register/', views.RegisterView.as_view(), name='api_register'),
    path('auth/login/', views.LoginView.as_view(), name='api_login'),
    path('users/me/', views.UserMeView.as_view(), name='api_user_me'),
    path('users/me/profile-image/', views.UserProfileImageUploadView.as_view(), name='api_profile_image'),
    path('users/me/teams/', views.MyTeamInfoView.as_view(), name='api_my_teams'),
    path('users/me/evaluations/', views.MyEvaluationsView.as_view(), name='api_my_evaluations'),
    path('users/me/jury-tournaments/', views.MyAssignedJuryTournamentsView.as_view(), name='api_my_jury_tournaments'),
    path('jury/registrations/', views.JuryTournamentRegistrationView.as_view(), name='api_jury_registration'),
    path('jury/registrations/pending/', views.JuryPendingRegistrationsView.as_view(), name='api_jury_registration_pending'),
    path('jury/registrations/<int:registration_id>/review/', views.JuryTournamentRegistrationReviewView.as_view(), name='api_jury_registration_review'),
    path('tournaments/', views.TournamentListCreateView.as_view(), name='api_tournaments'),
    path('tournaments/<int:tournament_id>/', views.TournamentDetailUpdateView.as_view(), name='api_tournament_detail'),
    path('tournaments/<int:tournament_id>/status/', views.TournamentStatusUpdateView.as_view(), name='api_tournament_status'),
    path('tournaments/<int:tournament_id>/image/', views.TournamentImageUploadView.as_view(), name='api_tournament_image'),
    path('tournaments/<int:tournament_id>/leaderboard/', views.TournamentLeaderboardView.as_view(), name='api_tournament_leaderboard'),
    path('tournaments/<int:tournament_id>/files/', views.TournamentFileListCreateView.as_view(), name='api_tournament_files'),
    path('tournaments/<int:tournament_id>/teams/', views.TournamentTeamsView.as_view(), name='api_tournament_teams'),
    path('teams/', views.TeamCreateView.as_view(), name='api_team_create'),
    path('teams/<int:team_id>/', views.TeamDetailAPIView.as_view(), name='api_team_detail'),
    path('teams/<int:team_id>/members/', views.TeamMemberListCreateView.as_view(), name='api_team_members'),
    path('teams/<int:team_id>/members/<int:member_id>/', views.TeamMemberDetailView.as_view(), name='api_team_member_detail'),
    path('teams/<int:team_id>/image/', views.TeamImageUploadView.as_view(), name='api_team_image'),
    path('members/<str:email>/tournaments/', views.MemberTournamentsView.as_view(), name='api_member_tournaments'),
    path('rounds/', views.RoundCreateView.as_view(), name='api_round_create'),
    path('rounds/<int:round_id>/', views.RoundDetailView.as_view(), name='api_round_detail'),
    path('rounds/<int:round_id>/distribute/', views.DistributeWorksView.as_view(), name='api_distribute_works'),
    path('submissions/', views.SubmissionCreateView.as_view(), name='api_submission_create'),
    path('evaluations/<int:evaluation_id>/', views.EvaluationDetailUpdateView.as_view(), name='api_evaluation_detail'),
    path('admin/teams/<int:team_id>/', views.AdminTeamDetailView.as_view(), name='admin_team_delete'),
    path('admin/members/<int:member_id>/', views.AdminMemberDeleteView.as_view(), name='admin_member_delete'),
    path('rounds/active/', views.ActiveTaskView.as_view(), name='api_active_round'),
]
